### ISSUE TITLE
Change from error to warning?

### ISSUE THREAD

**Issue by markkramerus** [FHIR/GoFSH#119]
I'm converting US Core to FSH. The IG has both JSON and XML definitions. GoFSH finds some XML files that are unrelated to resources (e.g. menu.xml) and reports errors when it can't make sense of them. I'm wondering if these errors should be warnings.
```
error Could not load FHIR-us-core.xml: Unknown resource type: specification
error Could not load fsh-generated\includes\menu.xml: Unknown resource type: ul
error Could not load input-cache\jiraspec.xml: Unknown resource type: specification
error Could not load input-cache\workgroups.xml: Unknown resource type: workgroups
```

**Comment by cmoesel** [comment]
I think that's fair.  The difficulty is that these errors come from the tool we use to translate XML to JSON -- so it's hard to know when a translation exception is expected (like in these cases) or if it truly represents corrupted XML or some other significant problem.  But it's probably safe to assume that if the error we get back from conversion is "Unknown resource type" then it's probably not really supposed to be a FHIR resource anyway, in which case it shouldn't be an error.

We could also completely ignore a few known file names like `menu.xml`, `jiraspec.cml`, and `workgroups.xml`.

Last, I don't know if we provide any guidance regarding how best to use GoFSH, but a few things come to mind:
* Running GoFSH on an entire IG source folder is often not the best way to use GoFSH because it may contain duplicate files (in input and output), incomplete files (no snapshot), extra files (in input-cache and others), etc.
* For best results, run GoFSH in json-only mode (which is the default) against the `output` folder of an IG after it has been built by IG Publisher, or against an unzipped IG download package.
* If running GoFSH against the final output of an IG is not possible, run it against the `input` folder rather than against the entire IG source folder.
