### ISSUE TITLE
Appending -of-X-Instance

### ISSUE THREAD

**Issue by citizenrich** [FHIR/GoFSH#121]
I have some Library and Measure resources that share the same ID. They are unique in their resource/path, e.g. /Library/Steve or /Measure/Steve, but it seems GoFSH doesn't like that one bit and appends to the IDs -of-Library-Steve etc. Is this a FSH thing or a GoFSH thing?

**Comment by cmoesel** [comment]
Thanks for asking this.  We'll take another look at the behavior here.  While FHIR does allow for duplicate ids in an IG (as long as they are different types), FSH allows you to reference entities by id -- so when there are duplicate ids, it can cause problems/confusion for SUSHI if an item is referenced by id and that id is assigned to multiple items.

That said, the way around this (for human authors) is to reference the item by name instead (if the name is unique) or by URL as a last resort (since that is guaranteed unique). Technically, GoFSH could probably do this too, in which case, duplicate ids would not be a problem.

We'll look into this to see what is feasible.

**Comment by cmoesel** [comment]
I'm also remembering now that I don't think SUSHI currently supports looking up _instances_ by URL -- so that could also be a reason for this behavior.  And I don't remember if the spec has anything to say about that or not.  Some instances don't even have canonical URLs, so it definitely wouldn't work in that case; but your example uses `Measure` and `Library` which do have canonical URLs, so it might be possible there.

**Comment by cmoesel** [comment]
BTW -- once you get the FSH from GoFSH, you can of course hand modify it to suit your needs.  So, I think you should be able to fix those instances by hand as long as your careful to ensure that you also fix any references to them.
