### ISSUE TITLE
Failure translating extension definitions to FSH

### ISSUE THREAD

**Issue by markkramerus** [FHIR/GoFSH#122]
This is a simple extension that should be readily convertible to FSH. GoFSH is coming up with the following FSH that is rejected by SUSHI:

```
* valueReference contains valueReference
* valueReference only Reference(HealthcareService)
```
The two files are attached (remove the .txt extensions).

[AssociatedHealthcareService-Extension.fsh.txt](https://github.com/FHIR/GoFSH/files/6592106/AssociatedHealthcareService-Extension.fsh.txt)

[structuredefinition-associated-healthcareservice.xml.txt](https://github.com/FHIR/GoFSH/files/6592096/structuredefinition-associated-healthcareservice.xml.txt)

**Comment by markkramerus** [comment]
Note that this is just one of many errors translating extensions in [hl7au/au-fhir-base](https://github.com/hl7au/au-fhir-base)

**Comment by markkramerus** [comment]
Here's another interesting one, translating AustralianIndigenousStatus extension:
```
* valueCoding contains valueCoding 1..
* valueCoding[valueCoding] only Coding
* valueCoding[valueCoding] from $australian-indigenous-status-1_1 (required)
* valueCoding[valueCoding] ^short = "Indigenous Status Code"
* valueCoding[valueCoding] ^definition = "NHDD based indigenous status code."
* valueCoding[valueCoding] ^binding.description = "Indigenous Status"
```

**Comment by cmoesel** [comment]
Nick and I have produced a fix for this in the PR linked above -- but it does not fix the last case you note (for AustralianIndigenousStatus).  The reason is because that case uses an `id` that I'm not even sure is valid.  It has this element:
```xml
<element id="Extension.valueCoding:valueCoding">
  <path value="Extension.valueCoding"/>
  <sliceName value="valueCoding"/>
  <short value="Indigenous Status Code"/>
  <definition value="NHDD based indigenous status code."/>
  <min value="1"/>
  <type>
    <code value="Coding"/>
  </type>
  <binding>
    <strength value="required"/>
    <description value="Indigenous Status"/>
    <valueSet value="https://healthterminologies.gov.au/fhir/ValueSet/australian-indigenous-status-1"/>
  </binding>
</element>
```

Note the id `Extension.valueCoding:valueCoding`.  AFAIK, `Extension.valueCoding` would be valid (because it implies the slicename) and `Extension.value[x]:valueCoding` would be valid (as the "formal" variant of the id), but I'm not sure that the approach they are using is valid because it's a hybrid of the two valid ones.  This is something we might want to look into to see if it is even valid before investing a lot of time in trying to fix it.

**Comment by cmoesel** [comment]
I've asked about this on Zulip: https://chat.fhir.org/#narrow/stream/179177-conformance/topic/Is.20Extension.2EvalueIdentifier.3AvalueIdentifier.20a.20valid.20id.3F
