### ISSUE TITLE
.text is currently ignored

### ISSUE THREAD

**Issue by patrick-werner** [FHIR/GoFSH#165]
Currently GoFSH ignores the .text element. Example: https://fshschool.org/FSHOnline/#/share/3yACorz

Expected behaviour:  
.text is also converted to FSH (at least optionally)

edit: providing json:
```
{
    "resourceType": "Composition",
    "id": "composition01",
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table><tr><td><b>Systolisch</b></td><td><b>Diastolisch</b></td><td><b>Einheit</b></td><td><b>Uhrzeit</b></td></tr><tr><td>140</td><td>110</td><td>mmHG</td><td>17:15h</td></tr></table></div>"
    }
}
```

**Comment by cmoesel** [comment]
This is actually intentional. Since the narrative is marked as generated, GoFSH does not decode it into FSH. This is under the assumption that generated narratives weren't a part of the original source -- and that the IG Publisher will re-generate them on build. GoFSH also does this if the narrative is marked as extensions (since that also means it is generated). If the status is not generated or extensions, however, GoFSH will decode the narrative into FSH.

If there is a use case for reproducing the generated narratives, we could consider making that a configuration point. But if not, the FSH looks a lot cleaner without all that generated narrative included in it!

**Comment by patrick-werner** [comment]
Makes a lot of sense! 
I wasn't aware about this FSH feature, will remove the generated tag.
