### ISSUE TITLE
Files in /output cause GoFSH to hang

### ISSUE THREAD

**Issue by markkramerus** [FHIR/GoFSH#53]
There are a set of json files that are generated by the IG Publisher as a matter or course and exist in the /output directory. The files include:
```
qa.json
canonicals.json
expansions.json
usage-stats.json
package.manifest.json
```
If someone wants GoFSH to convert publisher outputs to FSH files, GoFSH will hang. I believe `expansions.json `file is causing this.

My suggestion is to create a hardcoded "files to skip" list, and ignore these files.

**Comment by cmoesel** [comment]
Oh.  Hmmmm... I thought we already skipped files that were not obviously FHIR definitions -- but we still do have to read them and parse the contents in order to make that determination.  Either the reading/parsing is problematic or we're just not detecting them as non-interesting files.  Perhaps we will need to hard-code some exclusions.  We'll take a look!

**Comment by markkramerus** [comment]
Look at expansion.json -- it looks like a definition file. That's the thing.
