### ISSUE TITLE
Use of Index Instead of Slice Name Causes Error

### ISSUE THREAD

**Issue by markkramerus** [FHIR/GoFSH#57]
Again, this is from attempting to roundtrip from mCODE FHIR (latest master branch) to FSH via GoFSH, and back to FHIR using SUSHI.

SUSHI errors on the the following example because ctcae-grade slice is required (1..1), and the value ` $ctcae-grade-code-system#2 "Moderate Adverse Event"` is assigned to extension[0], which isn't the same as assigning it to extension[grade]:
```
Instance: ctc-adverse-event-example-1
InstanceOf: CTCAdverseEvent
Usage: #example
* contained[0] = mcode-medication-example-1
* extension[0].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/ctcae-grade"
* extension[0].valueCodeableConcept = $ctcae-grade-code-system#2 "Moderate Adverse Event"
* extension[1].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/adverse-event-expectation"
* extension[1].valueCodeableConcept = $ncithesaurus-stage#C41333 "Expected Adverse Event"
* extension[2].url = "http://hl7.org/fhir/us/mcode/StructureDefinition/adverse-event-resolved-date"
* extension[2].valueDateTime = "2020-05-21"
* actuality = #actual
---snip---
```

**Comment by cmoesel** [comment]
Oh boy.  I have a feeling that this is going to be a tough one.  In order to know what slice name to put, we would have to be able to analyze the data and figure out which of the slices it belongs to -- which, in the worst case, would require us to expand value sets to determine value set inclusion.

TBH, it may be that the only reasonable way to address this is to actually _relax_ the error in SUSHI so that it no longer counts "missing" slices as errors.  Or to put the logic in SUSHI to try to determine if an item fits in a slice.
